image: python:3.10.2-slim-bullseye

stages:
  - lint
  - build
  - deploy

include:
  - local: '/.gitlab/ci/pre-commit.yaml'
  - local: '/.gitlab/ci/mkdocs.yaml'

  # TODO: add "check markdown quality"
  # - local: '/.gitlab/ci/lint.yaml'
