site_name: SPIIR
site_description: 'A guide for the SPIIR low latency gravitational wave search Python library.'
site_author: 'Daniel Tang'
site_url: https://spiir-group.docs.ligo.org/spiir
repo_url: 'https://git.ligo.org/spiir-group/spiir'
repo_name: 'GitLab'
site_dir: public

theme:
  name: 'material_igwn'
  features:
    - navigation.expand
    - navigation.sections
    - navigation.tabs

nav:
  - Home: 'index.md'
  - 'User Guide':
    - 'Getting Started': user-guide/getting-started.md
    - Workflows: user-guide/workflows.md
  - Data:
    - Templates: data/templates.md
    - "IIR Filters": data/iir.md
    - "LIGO Light Weight": data/ligolw.md
  - Code Reference: reference/  # SUMMARY.md (literate-nav) from docs/generate_pages.py
  - About:
    - Contributing: about/contributing.md
    - License: about/license.md

plugins:
  - search
  - gen-files:
      scripts:
        - docs/generate_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: [src]  # search packages in the src folder
          options:
            docstring_style: numpy
            docstring_options:
              ignore_init_summary: yes
              merge_init_into_class: yes
              show_submodules: no
