mkdocs:
  stage: build
  before_script:
    - pip install -r docs/requirements.txt
  script:
    - mkdocs build --strict --verbose --site-dir test
  artifacts:
    paths:
    - test
  rules:
    - if:  $CI_PIPELINE_SOURCE == "merge_request_event"
    - if:  ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == "dev")

pages:
  stage: deploy
  before_script:
    - pip install -r docs/requirements.txt
  script:
    - mkdocs build --strict --verbose
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
